nfs_paths:
  /var/aegir/platforms: platforms
  /var/aegir/.cache: .valkyrie/cache
  /var/aegir/.drush/valkyrie: .valkyrie/valkyrie
ip: 10.42.0.10
tld: val
name: valkyrie
use_vagrant_dns: TRUE
manage_drushrc_aliases: TRUE
cpus: 2
vm_memory: 2048
vm_box: ubuntu/trusty64
public_network: FALSE
